export const SOCKET_CONNECTION_STATUS_CHANGED =
  'SOCKET_CONNECTION_STATUS_CHANGED';
export const SOCKET_TOPIC_SUBSCRIBE = 'SOCKET_TOPIC_SUBSCRIBE';
export const SOCKET_TOPIC_UNSUBSCRIBE = 'SOCKET_TOPIC_UNSUBSCRIBE';
export const SOCKET_TOPIC_SUBSCRIBE_ALL = 'SUBSCRIBE_ALL';
export const SOCKET_TOPIC_UNSUBSCRIBE_ALL = 'UNSUBSCRIBE_ALL';
